import type { Metadata } from "next";
import { Iosevka_Charon, Iosevka_Charon_Mono } from "next/font/google";
import "./globals.css";

const iosevkaCharon = Iosevka_Charon({
  variable: "--font-iosevka-sharon",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

const iosevkaCharonMono = Iosevka_Charon_Mono({
  variable: "--font-iosevka-sharon-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${iosevkaCharon.variable} ${iosevkaCharonMono.variable} h-full antialiased overflow-x-hidden`}
    >
      <body className="min-h-full flex flex-col overflow-x-auto">
        {children}
      </body>
    </html>
  );
}
